language: ruby
rvm:
- 2.3.3

before_script:
  - chmod +x ./cibuild

# Assume bundler is being used, therefore the 'install' step will
# run 'bundle install' by default.
script: ./cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up the installation of html-proofer

sudo: false # Route this build to the container-based infrastructure for a faster build
