# Site settings
title: Steve Mayes
description: >
  Steve is an MCP, member of ACM, and a double graduate of Case Western Reserve University.
  His passion is technology. His focus is architecting and developing cloud solutions.
baseurl: ""
url: "https://smayes.com"

# Build settings
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
jekyll-archives:
  enabled:
    - month
  layouts:
    month: archive
  permalinks:
    month: "/:year/:month/"
markdown: kramdown
paginate: 5
paginate_path: "/blog/:num"
sass:
  style: compressed
timezone: US/Eastern

# Default YAML
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: ":year/:month/:slug"
      layout: "post"
